# Kind deployment that forces the Cluster to be amd64
# useful for architecture-dependant Mac M1 devlopment
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node-amd64:v1.26.0