Vagrant.configure("2") do |config|
    config.vm.box = "fedora/36-cloud-base"
    config.vm.provider "virtualbox" do |v|
        v.name = "Fedora 36"
        v.cpus = 2
        v.memory = 4096
    end

    # sharing info with host
    config.vm.synced_folder "~", "/vagrant", type: "virtualbox"
end
