Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.provider "virtualbox" do |v|
        v.name = "Ubuntu 20.04"
        v.cpus = 2
        v.memory = 4096
    end

    # sharing info with host
    config.vm.synced_folder "~", "/vagrant", type: "virtualbox"
end
